### ISSUE TITLE
When are you going to start using the new logo?

### ISSUE THREAD

**Issue by skibum55** [starkandwayne/ultimate-guide-to-bosh#16]
When are you going to start using the new logo?
![cff-symbol-bosh-full-color](https://user-images.githubusercontent.com/3813241/31641771-217842de-b2a4-11e7-8bef-8eae86c355f3.png)
from https://cloudfoundry.org/bosh/

**Comment by drnic** [comment]
There is indeed a lot to like about the new logo.

________________________________

**Comment by drnic** [comment]
I'll worry about updating the "book cover" image later when I revisit the book cover itself.
