### ISSUE TITLE
Definition of integers in BOSH that have underscores

### ISSUE THREAD

**Issue by norman-abramovitz** [starkandwayne/ultimate-guide-to-bosh#24]
I was using this new guide while giving highlights about BOSH on the dojo I am on.     A question was asked about the underscore in numbers.   There does not seem to be a definition on Bosh.io.   I am wondering if that should be explained somewhere in this guide.  

I am wondering if we should say something about that underscores makes the number the more readable somewhere.

**Comment by drnic** [comment]
It's a good question. I can't spot it in http://www.yaml.org/spec/current.html

In https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#underscores-stripped-in-integer-definitions it says:

> If a definition only includes numbers and underscores, it is parsed by YAML as an integer and all underscores are stripped. To ensure the object becomes a string, it should be surrounded by quotes. More information [here](https://stackoverflow.com/questions/2723321/snakeyaml-how-to-disable-underscore-stripping-when-parsing).
> Here's an example:

```
>>> import yaml
>>> yaml.safe_load('2013_05_10')
20130510
>>> yaml.safe_load('"2013_05_10"')
'2013_05_10'
```
